Repository ad-earth/admin-v2.0, pull requests merged in 2023-04, with the labels that each got.

#18 Feat/sol
  .eslintrc
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
  src/App.tsx
  src/components/logIn/LogInForm.tsx
  src/components/logIn/logInForm.module.scss
  src/elements/Button.tsx
  src/elements/button.module.scss
  src/elements/test.ts
  src/pages/LogInPage.tsx
  src/pages/logInPage.module.scss
  src/shared/styles/_mixins.scss
  src/shared/styles/index.scss
  tsconfig.json
  yarn.lock
Labels: enhancement

#17 Feat/dam
  .gitignore
  package-lock.json
  package.json
  public/assets/down.png
  src/components/productpost/Editor.tsx
  src/components/productpost/Option.tsx
  src/components/productpost/PostForm.tsx
  src/components/productpost/Thumbnail.tsx
  src/components/productpost/editor.module.scss
  src/components/productpost/option.module.scss
  src/components/productpost/postForm.module.scss
  src/components/productpost/thumbnail.module.scss
  src/constants/index.ts
  src/constants/queryKeys.ts
  src/elements/DropDown.tsx
  src/elements/Input.tsx
  src/elements/dropDown.module.scss
  src/elements/input.module.scss
  src/pages/ProductPostPage.tsx
  src/pages/productPostPage.module.scss
  src/shared/api/imageUploader.ts
  src/shared/styles/_mixins.scss
  src/shared/utils/s3Config.ts
  yarn.lock
Labels: enhancement

#19 Feat/sol
  src/App.tsx
  src/components/logIn/LogInForm.tsx
  src/components/logIn/logInForm.module.scss
  src/constants/index.ts
  src/elements/Button.tsx
  src/elements/button.module.scss
  src/hooks/test.ts
  src/hooks/useRegExp.ts
  src/pages/logInPage.module.scss
  src/query/test.ts
  src/query/useLogin.ts
  src/shared/api/apis.ts
  src/shared/api/instance.ts
  src/shared/styles/_mixins.scss
  yarn.lock
Labels: enhancement

#21 Feat/sol
  src/components/account/FindFormBox.tsx
  src/components/account/Form.tsx
  src/components/account/IdForm.tsx
  src/components/account/PwdForm.tsx
  src/components/account/findFormBox.module.scss
  src/components/account/form.module.scss
  src/components/account/idForm.module.scss
  src/constants/queryKeys.ts
  src/elements/Button.tsx
  src/elements/button.module.scss
  src/pages/AccountPage.tsx
  src/pages/ProtectedRoute.tsx
  src/pages/accountPage.module.scss
  src/query/useId.ts
  src/query/useNewPassword.ts
  src/query/usePassword.ts
  src/shared/api/apis.ts
  src/shared/api/instance.ts
  src/shared/styles/_mixins.scss
  src/shared/types/types.ts
  yarn.lock
Labels: enhancement

#22 Feat/suin 메인페이지 개발
  package-lock.json
  package.json
  public/assets/adBannerCharacter.svg
  public/assets/bizBg.svg
  public/assets/icon/bizMoney.svg
  public/assets/icon/exposedProd.svg
  public/assets/icon/lastMonth.svg
  public/assets/icon/newOrder.svg
  public/assets/slideBanner1.png
  public/assets/slideBanner2.png
  public/assets/slideBanner3.png
  src/components/banner/AccordionItem.tsx
  src/components/banner/AuthSlideBanner.tsx
  src/components/banner/MainAccordionBanner.tsx
  src/components/banner/MainAdBanner.tsx
  src/components/banner/accordionItem.module.scss
  src/components/banner/authSlideBanner.module.scss
  src/components/banner/mainAccordionBanner.module.scss
  src/components/banner/mainAdBanner.module.scss
  src/components/common/Board.tsx
  src/components/common/board.module.scss
  src/components/layout/AuthLayout.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/layout/authLayout.module.scss
  src/components/main/AdSummary.tsx
  src/components/main/BizMoney.tsx
  src/components/main/BoardContent.tsx
  src/components/main/KeywordRanking.tsx
  src/components/main/adSummary.module.scss
  src/components/main/bizMoney.module.scss
  src/components/main/boardContent.module.scss
  src/components/main/keywordRanking.module.scss
  src/components/modal/GlobalModal.tsx
  src/components/modal/LogoutModal.tsx
  src/components/modal/PostAdModal.tsx
  src/components/modal/WithdrawalModal.tsx
  src/components/modal/logoutModal.module.scss
  src/components/modal/withdrawalModal.module.scss
  src/hooks/useModal.ts
  src/hooks/useViewport.ts
  src/pages/MainPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/mainPage.module.scss
  src/pages/notFoundPage.module.scss
  src/query/useBizMoney.ts
  src/query/useMainDashboard.ts
  src/query/useUser.ts
  src/shared/api/apis.ts
  src/shared/api/instance.ts
  src/shared/styles/_colors.scss
  src/shared/types/types.ts
  src/shared/utils/Router.tsx
  src/store/modal.ts
  yarn.lock
Labels: enhancement

#24 Feat/sol
  src/components/common/test.ts
  src/components/productpost/PostForm.tsx
  src/components/report/AdChart.tsx
  src/components/report/AdTable.tsx
  src/components/report/Filter.tsx
  src/components/report/adChart.module.scss
  src/components/report/adTable.module.scss
  src/components/report/filter.module.scss
  src/constants/index.ts
  src/constants/queryKeys.ts
  src/elements/DatePicker.tsx
  src/elements/DropDown.tsx
  src/elements/TableHead.tsx
  src/elements/datePicker.module.scss
  src/hooks/useMinDate.ts
  src/pages/ReportPage.tsx
  src/pages/reportPage.module.scss
  src/query/useProducts.ts
  src/query/useReport.ts
  src/shared/api/apis.ts
  src/shared/styles/_mixins.scss
  src/shared/types/types.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#25 Feat/sol
  package-lock.json
  package.json
  src/components/report/AdChart.tsx
  src/components/report/AdTable.tsx
  src/components/report/Filter.tsx
  src/constants/index.ts
  src/elements/DatePicker.tsx
  src/elements/TableHead.tsx
  src/elements/tableHead.module.scss
  src/hooks/useMinDate.ts
  src/hooks/useTerm.ts
  src/pages/ReportPage.tsx
  src/shared/api/apis.ts
  src/shared/types/types.ts
  yarn.lock
Labels: enhancement

#29 Feat/sol
  src/components/layout/Nav.tsx
  src/components/report/AdChart.tsx
  src/components/report/adChart.module.scss
  src/hooks/useTerm.ts
Labels: enhancement, refactoring

#33 Feat/dam
  src/components/modal/GlobalModal.tsx
  src/components/modal/ProductDeleteModal.tsx
  src/components/productpost/PostForm.tsx
  src/elements/button.module.scss
  src/shared/api/imageUploader.ts
  src/store/modal.ts
Labels: enhancement

#32 feat. 광고보고서 테이블 기본 정렬 설정 #5
  src/components/report/AdTable.tsx
  src/query/useReport.ts
Labels: enhancement

#36 Feat/suin 광고관리페이지, 키워드 등록모달 ,키워드 수정모달 개발
  public/assets/icon/cancel.svg
  public/assets/icon/info.svg
  src/components/adSet/AdSetButtonBox.tsx
  src/components/adSet/AdSetTable.tsx
  src/components/adSet/adSetButtonBox.module.scss
  src/components/adSet/adSetTable.module.scss
  src/components/layout/Nav.tsx
  src/components/modal/GlobalModal.tsx
  src/components/modal/PostAdModal.tsx
  src/components/modal/ProductDeleteModal.tsx
  src/components/modal/ProductStatusModal.tsx
  src/components/modal/postAdModal/Form.tsx
  src/components/modal/postAdModal/PostAdModal.tsx
  src/components/modal/postAdModal/Switch.style.ts
  src/components/modal/postAdModal/Switch.tsx
  src/components/modal/postAdModal/Table.tsx
  src/components/modal/postAdModal/TooltipTiltle.tsx
  src/components/modal/postAdModal/form.module.scss
  src/components/modal/postAdModal/postAdModal.module.scss
  src/components/modal/postAdModal/table.module.scss
  src/components/modal/postAdModal/tooltipTiltle.module.scss
  src/components/modal/productStatusModal.module.scss
  src/components/productSet/ProductSetTable.tsx
  src/components/productSet/tableSwitch.style.ts
  src/constants/index.ts
  src/elements/Button.tsx
  src/elements/DropDown.tsx
  src/elements/button.module.scss
  src/pages/AdSetPage.tsx
  src/pages/ProductSetPage.tsx
  src/pages/adSetPage.module.scss
  src/query/useAdFilter.ts
  src/query/useAdManagement.ts
  src/query/useAdkeyword.ts
  src/query/useProdManagement.ts
  src/query/useProduct.ts
  src/shared/api/apis.ts
  src/shared/types/types.ts
  src/store/modal.ts
Labels: enhancement

#43 Refac/dam
  src/components/productpost/Editor.tsx
  src/components/productpost/Option.tsx
  src/components/productpost/PostForm.tsx
  src/components/service/ServiceTable.tsx
  src/hooks/useOption.ts
  src/pages/SignupPage.tsx
  src/query/useGetProduct.ts
  src/shared/utils/RouterList.tsx
Labels: refactoring

#44 fix. 회원가입 에러메세지 오류수정
  src/components/signup/SignupForm.tsx
Labels: bug

#45 Refactoring
  src/components/productpost/Editor.tsx
  src/components/productpost/Option.tsx
  src/components/productpost/PostForm.tsx
  src/components/service/ServiceTable.tsx
  src/hooks/useOption.ts
  src/query/useGetProduct.ts
Labels: refactoring

#46 Feat/suin 상품관리, 광고관리 버그 수정 ,이미지 사이즈 추가
  src/components/adSet/AdSetButtonBox.tsx
  src/components/layout/header.module.scss
  src/components/main/bizMoney.module.scss
  src/components/modal/postAdModal/KeywordForm.tsx
  src/components/modal/postAdModal/PostAdModal.tsx
  src/components/modal/postAdModal/keywordForm.module.scss
  src/components/modal/postAdModal/postAdModal.module.scss
  src/components/modal/postAdModal/table.module.scss
  src/pages/AdSetPage.tsx
  src/pages/ProductSetPage.tsx
  src/pages/signupPage.module.scss
Labels: bug, enhancement

#48 Refac/dam
  README.md
  src/components/adSet/AdSetButtonBox.tsx
  src/components/layout/Nav.tsx
  src/components/layout/header.module.scss
  src/components/main/bizMoney.module.scss
  src/components/modal/postAdModal/KeywordForm.tsx
  src/components/modal/postAdModal/PostAdModal.tsx
  src/components/modal/postAdModal/keywordForm.module.scss
  src/components/modal/postAdModal/postAdModal.module.scss
  src/components/modal/postAdModal/table.module.scss
  src/elements/DatePicker.tsx
  src/hooks/useDate.ts
  src/hooks/useMinDate.ts
  src/pages/AdSetPage.tsx
  src/pages/ProductSetPage.tsx
  src/pages/signupPage.module.scss
Labels: bug

#49 Refactoring
  src/components/layout/Nav.tsx
  src/elements/DatePicker.tsx
  src/hooks/useDate.ts
  src/hooks/useMinDate.ts
Labels: bug

#52 Fix/sol
  src/components/report/AdChart.tsx
  src/hooks/useDate.ts
  src/hooks/useOffsetDate.ts
  src/hooks/useTerm.ts
  src/pages/ReportPage.tsx
  yarn.lock
Labels: debug

#55 Refac/suin 광고관리,상품관리페이지 버그수정
  README.md
  src/components/adSet/AdSetTable.tsx
  src/components/modal/ProductDeleteModal.tsx
  src/components/modal/postAdModal/PostAdModal.tsx
  src/components/productpost/PostForm.tsx
  src/pages/AdSetPage.tsx
  src/pages/ProductSetPage.tsx
  src/query/useProduct.ts
Labels: debug, enhancement

#68 refactor. 배송관리 옵션 툴팁 추가
  src/components/service/ServiceTable.tsx
  src/shared/types/types.ts
Labels: refactoring

#70 refactor. 로그인 리팩토링 #59
  src/components/logIn/LogInForm.tsx
  src/query/useLogin.ts
Labels: refactoring

#71 fix. 가격 & 할인율 유효성 검증 추가
  src/components/productpost/PostForm.tsx
  src/constants/index.ts
Labels: debug

#72 Fix/dam
  .gitignore
  src/components/productpost/Option.tsx
  src/components/productpost/PostForm.tsx
Labels: debug
